import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb, RGB } from "pdf-lib";
import { RepositoryScanResult } from "../scanner/scanResult";

// ---------------------------------------------------------------------------
// Design tokens
// ---------------------------------------------------------------------------

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 40;
const CONTENT_W = PAGE_W - MARGIN * 2;

const COLORS = {
  bg: rgb(1, 1, 1),
  headerBar: rgb(0.11, 0.16, 0.32), // deep navy
  primary: rgb(0.16, 0.38, 0.92), // accent blue
  text: rgb(0.11, 0.11, 0.14),
  textMuted: rgb(0.45, 0.47, 0.53),
  border: rgb(0.87, 0.88, 0.92),
  chipBg: rgb(0.94, 0.95, 0.98),
  chipBorder: rgb(0.82, 0.85, 0.93),
  green: rgb(0.09, 0.55, 0.36),
  greenBg: rgb(0.9, 0.97, 0.93),
  orange: rgb(0.82, 0.53, 0.06),
  orangeBg: rgb(0.99, 0.95, 0.87),
  red: rgb(0.78, 0.19, 0.19),
  redBg: rgb(0.99, 0.91, 0.91),
  track: rgb(0.9, 0.91, 0.94),
};

const FOOTER_TEXT = "Generated by Repo Scanner";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export async function generateRepositoryPdf(
  repositoryName: string,
  scannedAt: string,
  report: RepositoryScanResult,
) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const ctx = new PdfWriter(pdf, font, bold);

  ctx.drawCover(repositoryName, scannedAt, report);

  ctx.sectionHeader("Security");
  ctx.scoreLine("Security Score", report.security.score);
  ctx.gap(6);

  if (report.security.issues.length === 0) {
    ctx.badgeInline("No security issues detected", COLORS.green, COLORS.greenBg);
  } else {
    report.security.issues.forEach((issue) => ctx.issueCard(issue));
  }

  ctx.sectionSpacer();
  ctx.sectionHeader("Repository Summary");
  ctx.statRow([
    { label: "Files", value: String(report.totalFiles) },
    { label: "Directories", value: String(report.totalDirectories) },
    { label: "Lines of Code", value: String(report.totalLines) },
  ]);

  ctx.sectionSpacer();
  ctx.sectionHeader("Project Metrics");
  ctx.keyValueList(
    Object.entries(report.metrics).map(([k, v]) => [k, String(v)]),
  );

  const badgeSections: [string, Record<string, boolean>][] = [
    ["Frameworks", report.frameworks],
    ["Package Managers", report.packageManager],
    ["Docker", report.docker],
    ["CI/CD", report.ci],
    ["Database", report.database],
    ["Testing", report.testing],
    ["Code Quality", report.quality],
    ["Environment", report.environment],
    ["Project Structure", report.structure],
  ];

  badgeSections.forEach(([title, obj]) => {
    const enabled = Object.entries(obj)
      .filter(([, on]) => on)
      .map(([name]) => name);

    if (enabled.length === 0) return;

    ctx.sectionSpacer();
    ctx.subHeader(title);
    ctx.badgeGrid(enabled);
  });

  ctx.sectionSpacer();
  ctx.sectionHeader("Detected File Extensions");
  ctx.keyValueList(
    Object.entries(report.extensions).map(([ext, count]) => [
      ext,
      String(count),
    ]),
  );

  ctx.sectionSpacer();
  ctx.sectionHeader("Detected Technologies");
  if (report.score.passed.length === 0) {
    ctx.mutedLine("None detected.");
  } else {
    ctx.checklist(report.score.passed, true);
  }

  ctx.sectionSpacer();
  ctx.sectionHeader("Missing Technologies");
  if (report.score.missing.length === 0) {
    ctx.mutedLine("Nothing missing - great coverage!");
  } else {
    ctx.checklist(report.score.missing, false);
  }

  ctx.finalizeFooters();

  const bytes = await pdf.save();
  const blob = new Blob([new Uint8Array(bytes)], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${repositoryName.replace("/", "-")}-report.pdf`;
  a.click();

  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Writer helper — owns page/cursor state and all drawing primitives
// ---------------------------------------------------------------------------

class PdfWriter {
  private page: PDFPage;
  private y = 0;

  constructor(
    private pdf: PDFDocument,
    private font: PDFFont,
    private bold: PDFFont,
  ) {
    this.page = this.pdf.addPage([PAGE_W, PAGE_H]);
    this.y = PAGE_H - MARGIN;
  }

  // ---- low level -----------------------------------------------------

  private newPage() {
    this.page = this.pdf.addPage([PAGE_W, PAGE_H]);
    this.y = PAGE_H - MARGIN;
  }

  private ensureSpace(height: number) {
    if (this.y - height < MARGIN + 30) this.newPage();
  }

  private text(
    str: string,
    x: number,
    y: number,
    size: number,
    useBold = false,
    color: RGB = COLORS.text,
  ) {
    this.page.drawText(str, {
      x,
      y,
      size,
      font: useBold ? this.bold : this.font,
      color,
    });
  }

  private wrap(str: string, size: number, maxWidth: number, useBold = false): string[] {
    const f = useBold ? this.bold : this.font;
    const words = str.split(" ");
    const lines: string[] = [];
    let current = "";

    words.forEach((word) => {
      const candidate = current ? `${current} ${word}` : word;
      if (f.widthOfTextAtSize(candidate, size) > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = candidate;
      }
    });
    if (current) lines.push(current);
    return lines;
  }

  gap(px: number) {
    this.y -= px;
  }

  sectionSpacer() {
    this.y -= 18;
  }

  // ---- cover -----------------------------------------------------------

  drawCover(repositoryName: string, scannedAt: string, report: RepositoryScanResult) {
    // header bar
    const barH = 120;
    this.page.drawRectangle({
      x: 0,
      y: PAGE_H - barH,
      width: PAGE_W,
      height: barH,
      color: COLORS.headerBar,
    });

    this.text("Repo Scanner", MARGIN, PAGE_H - 45, 22, true, rgb(1, 1, 1));
    this.text(
      "Repository Analysis Report",
      MARGIN,
      PAGE_H - 68,
      12,
      false,
      rgb(0.8, 0.84, 0.95),
    );
    this.text(repositoryName, MARGIN, PAGE_H - 95, 15, true, rgb(1, 1, 1));
    this.text(
      `Generated ${new Date(scannedAt).toLocaleString()}`,
      MARGIN,
      PAGE_H - 112,
      10,
      false,
      rgb(0.8, 0.84, 0.95),
    );

    this.y = PAGE_H - barH - 35;

    // overall score card
    this.sectionHeader("Repository Health");
    this.scoreGauge(report.score.overall, report.score.rating);
    this.sectionSpacer();
  }

  // ---- headers -----------------------------------------------------------

  sectionHeader(title: string) {
    this.ensureSpace(30);
    this.page.drawRectangle({
      x: MARGIN,
      y: this.y - 4,
      width: 4,
      height: 18,
      color: COLORS.primary,
    });
    this.text(title, MARGIN + 12, this.y, 15, true);
    this.y -= 26;
  }

  subHeader(title: string) {
    this.ensureSpace(20);
    this.text(title, MARGIN, this.y, 11.5, true, COLORS.textMuted);
    this.y -= 16;
  }

  mutedLine(text: string) {
    this.ensureSpace(16);
    this.text(text, MARGIN, this.y, 10.5, false, COLORS.textMuted);
    this.y -= 18;
  }

  // ---- score visuals -------------------------------------------------

  private ratingColors(rating: string): { fg: RGB; bg: RGB } {
    const r = rating.toLowerCase();
    if (r.includes("excellent") || r.includes("good"))
      return { fg: COLORS.green, bg: COLORS.greenBg };
    if (r.includes("fair") || r.includes("average"))
      return { fg: COLORS.orange, bg: COLORS.orangeBg };
    return { fg: COLORS.red, bg: COLORS.redBg };
  }

  scoreGauge(score: number, rating: string) {
    this.ensureSpace(50);
    const { fg, bg } = this.ratingColors(rating);
    const barW = CONTENT_W - 90;
    const barH = 14;
    const barX = MARGIN;
    const barY = this.y - barH;

    // track
    this.page.drawRectangle({
      x: barX,
      y: barY,
      width: barW,
      height: barH,
      color: COLORS.track,
    });
    // fill
    this.page.drawRectangle({
      x: barX,
      y: barY,
      width: (Math.max(0, Math.min(100, score)) / 100) * barW,
      height: barH,
      color: fg,
    });

    this.text(`${score}/100`, barX + barW + 12, barY + 2, 12, true, COLORS.text);

    this.y = barY - 20;

    // rating pill
    const label = rating.toUpperCase();
    const padX = 8;
    const pillW = this.bold.widthOfTextAtSize(label, 9) + padX * 2;
    this.page.drawRectangle({
      x: MARGIN,
      y: this.y - 14,
      width: pillW,
      height: 18,
      color: bg,
    });
    this.text(label, MARGIN + padX, this.y - 9, 9, true, fg);
    this.y -= 30;
  }

  scoreLine(label: string, score: number) {
    this.ensureSpace(16);
    this.text(`${label}:`, MARGIN, this.y, 11, true);
    const fg =
      score >= 80 ? COLORS.green : score >= 50 ? COLORS.orange : COLORS.red;
    this.text(
      `${score}/100`,
      MARGIN + this.bold.widthOfTextAtSize(`${label}:`, 11) + 8,
      this.y,
      11,
      true,
      fg,
    );
    this.y -= 20;
  }

  // ---- issue cards -----------------------------------------------------

  private severityStyle(sev: string): { fg: RGB; bg: RGB } {
    const s = sev.toLowerCase();
    if (s.includes("crit") || s.includes("high"))
      return { fg: COLORS.red, bg: COLORS.redBg };
    if (s.includes("med"))
      return { fg: COLORS.orange, bg: COLORS.orangeBg };
    return { fg: COLORS.textMuted, bg: COLORS.chipBg };
  }

  issueCard(issue: { severity: string; file: string; line: number; message: string }) {
    const { fg, bg } = this.severityStyle(issue.severity);
    const location = `${issue.file}:${issue.line}`;
    const msgLines = this.wrap(issue.message, 10, CONTENT_W - 20);
    const cardH = 34 + msgLines.length * 13;

    this.ensureSpace(cardH + 8);

    const top = this.y;
    this.page.drawRectangle({
      x: MARGIN,
      y: top - cardH,
      width: CONTENT_W,
      height: cardH,
      color: rgb(0.99, 0.99, 1),
      borderColor: COLORS.border,
      borderWidth: 1,
    });

    // severity pill
    const sevLabel = issue.severity.toUpperCase();
    const pillW = this.bold.widthOfTextAtSize(sevLabel, 8) + 14;
    this.page.drawRectangle({
      x: MARGIN + 10,
      y: top - 20,
      width: pillW,
      height: 15,
      color: bg,
    });
    this.text(sevLabel, MARGIN + 17, top - 15.5, 8, true, fg);

    this.text(location, MARGIN + 10 + pillW + 10, top - 15.5, 9.5, true, COLORS.textMuted);

    let ly = top - 32;
    msgLines.forEach((line) => {
      this.text(line, MARGIN + 10, ly, 10, false, COLORS.text);
      ly -= 13;
    });

    this.y = top - cardH - 10;
  }

  // ---- generic layout helpers -----------------------------------------

  badgeInline(label: string, fg: RGB, bg: RGB) {
    this.ensureSpace(24);
    const padX = 10;
    const w = this.font.widthOfTextAtSize(label, 10) + padX * 2;
    this.page.drawRectangle({
      x: MARGIN,
      y: this.y - 14,
      width: w,
      height: 18,
      color: bg,
    });
    this.text(label, MARGIN + padX, this.y - 9, 10, false, fg);
    this.y -= 26;
  }

  badgeGrid(items: string[]) {
    const chipH = 20;
    const padX = 10;
    const gap = 8;
    let x = MARGIN;

    this.ensureSpace(chipH + 4);

    items.forEach((label) => {
      const w = this.font.widthOfTextAtSize(label, 9.5) + padX * 2;

      if (x + w > MARGIN + CONTENT_W) {
        x = MARGIN;
        this.y -= chipH + 6;
        this.ensureSpace(chipH + 4);
      }

      this.page.drawRectangle({
        x,
        y: this.y - chipH + 4,
        width: w,
        height: chipH,
        color: COLORS.chipBg,
        borderColor: COLORS.chipBorder,
        borderWidth: 0.75,
      });
      this.text(label, x + padX, this.y - chipH + 10, 9.5, false, COLORS.text);

      x += w + gap;
    });

    this.y -= chipH + 10;
  }

  statRow(stats: { label: string; value: string }[]) {
    const colW = CONTENT_W / stats.length;
    this.ensureSpace(46);
    const top = this.y;

    stats.forEach((s, i) => {
      const x = MARGIN + i * colW;
      this.page.drawRectangle({
        x,
        y: top - 42,
        width: colW - 8,
        height: 42,
        color: COLORS.chipBg,
        borderColor: COLORS.chipBorder,
        borderWidth: 0.75,
      });
      this.text(s.value, x + 10, top - 18, 16, true, COLORS.primary);
      this.text(s.label, x + 10, top - 34, 9, false, COLORS.textMuted);
    });

    this.y = top - 52;
  }

  keyValueList(pairs: [string, string][]) {
    const rowH = 18;
    pairs.forEach(([k, v], i) => {
      this.ensureSpace(rowH);
      if (i % 2 === 0) {
        this.page.drawRectangle({
          x: MARGIN,
          y: this.y - rowH + 5,
          width: CONTENT_W,
          height: rowH,
          color: rgb(0.97, 0.97, 0.99),
        });
      }
      this.text(k, MARGIN + 6, this.y - 7, 10, false, COLORS.text);
      this.text(v, MARGIN + CONTENT_W - 6 - this.bold.widthOfTextAtSize(v, 10), this.y - 7, 10, true, COLORS.text);
      this.y -= rowH;
    });
    this.y -= 8;
  }

  // Draws a small vector check mark (avoids relying on font glyph coverage,
  // since standard WinAnsi fonts can't encode ✓/✕).
  private drawCheck(x: number, yBase: number, color: RGB) {
    this.page.drawLine({
      start: { x: x, y: yBase + 3 },
      end: { x: x + 3, y: yBase },
      thickness: 1.4,
      color,
    });
    this.page.drawLine({
      start: { x: x + 3, y: yBase },
      end: { x: x + 9, y: yBase + 7 },
      thickness: 1.4,
      color,
    });
  }

  private drawCross(x: number, yBase: number, color: RGB) {
    this.page.drawLine({
      start: { x, y: yBase },
      end: { x: x + 8, y: yBase + 8 },
      thickness: 1.4,
      color,
    });
    this.page.drawLine({
      start: { x, y: yBase + 8 },
      end: { x: x + 8, y: yBase },
      thickness: 1.4,
      color,
    });
  }

  checklist(items: string[], positive: boolean) {
    const fg = positive ? COLORS.green : COLORS.red;
    items.forEach((item) => {
      this.ensureSpace(16);
      if (positive) {
        this.drawCheck(MARGIN, this.y - 2, fg);
      } else {
        this.drawCross(MARGIN, this.y - 2, fg);
      }
      this.text(item, MARGIN + 16, this.y, 10.5, false, COLORS.text);
      this.y -= 17;
    });
    this.y -= 6;
  }

  // ---- footers ---------------------------------------------------------

  finalizeFooters() {
    const pages = this.pdf.getPages();
    pages.forEach((p, i) => {
      p.drawLine({
        start: { x: MARGIN, y: 30 },
        end: { x: PAGE_W - MARGIN, y: 30 },
        thickness: 0.75,
        color: COLORS.border,
      });
      p.drawText(FOOTER_TEXT, {
        x: MARGIN,
        y: 18,
        size: 8,
        font: this.font,
        color: COLORS.textMuted,
      });
      const pageLabel = `Page ${i + 1} of ${pages.length}`;
      const w = this.font.widthOfTextAtSize(pageLabel, 8);
      p.drawText(pageLabel, {
        x: PAGE_W - MARGIN - w,
        y: 18,
        size: 8,
        font: this.font,
        color: COLORS.textMuted,
      });
    });
  }
}